### ISSUE TITLE
wrong key in info how to switch picks

### ISSUE THREAD

**Issue by TeeTeeHaa** [BBelk/StarfieldDigipickSim#1]
On the top right it say "Q/E to switch picks". Actually it should say "Q/W to switch picks".

On the bottom center it says "E Slot". It might even say "E/Space Slot".

Personally I'd suggest to switch picks with "Q/E" and slot with "W/S/Space".

game v0.2.1
Firefox 117.0.1 (64-bit) and Edge Version 117.0.2045.41 (Official build) (64-bit)

P.S.: Nice mini game. I have not played Starfield. Yet. I feel better prepared now. 🗝️

**Comment by BBelk** [comment]
Fixed, thanks!

**Comment by TeeTeeHaa** [comment]
You're welcome.

P.S.: I played Starfield meanwhile and successfully opened the first safe I found because I knew what to do because of your minigame. 👍
